### ISSUE TITLE
Feature request: Avoid ambiguous characters

### ISSUE THREAD

**Issue by kevinp2** [cxam/passed.pw#2]
I like this password generator a lot, especially for mobile devices.

An additional option for those who have to type in passwords would be: Avoid ambiguous characters.

LastPass has this feature.  If selected, the following characters are excluded from the generated password:
The letters o, O, i and I, l (ell) and L
The numbers 0 and 1

It would be great if this could be implemented!  Thank you in advance

**Comment by cxam** [comment]
Thanks for the suggestion and glad you like the generator. I've been keeping the UI within a viewport of 320x480px and adding an extra option does break this a bit (left). Just experimented with the ambiguous option added (right), what do you think?

![passed_pw_ambiguous_viewport](https://cloud.githubusercontent.com/assets/7763217/12054377/14ab07b4-af1b-11e5-91db-cc4a75905dd0.png)

**Comment by kevinp2** [comment]
This looks great, very clean!  If the first three checkboxes are selected
by default, I think they become self-explanatory and no longer need the
"Capital Letters", etc.

Do you remember the choices from the last visit?

On Wed, Dec 30, 2015 at 11:32 AM, cxam notifications@github.com wrote:

> Thanks for the suggestion and glad you like the generator. I've been
> keeping the UI within a viewport of 320x480px and adding an extra option
> does break this a bit. Just experimented with the ambiguous option added
> (right), what do you think?
> 
> [image: passed_pw_ambiguous_viewport]
> https://cloud.githubusercontent.com/assets/7763217/12054377/14ab07b4-af1b-11e5-91db-cc4a75905dd0.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cxam/passed.pw/issues/2#issuecomment-168040673.

## 

Principal Consultant
_KP Automation_
kevin@kpautomation.com
http://www.kpautomation.com
+1 (512) 394-4421

**Comment by cxam** [comment]
Appreciate the feedback. The updated UI and avoid ambiguity feature is now live, let me know if you have an issues, thanks.

Currently, the defaults include numbers, letters, common punctuation and other characters. I've kept these the same in this version as I would rather leave the option to reduce complexity up to the user. The selected options can be saved by clicking on the save button, providing local storage is available and is allowed to be accessed. Any saved options will then be used in future visits.

**Comment by kevinp2** [comment]
Awesome!  I have posted about it on my blog: http://www.kpautomation.com/wp/passed-pw-generate-passwords-friendly-to-smartphones-and-mobile-devices/
