### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by jasonpearce** [cxam/passed.pw#4]
Looks like your site is down:
https://downforeveryoneorjustme.com/passed.pw

Please come back. I thought it was great.

**Comment by cxam** [comment]
Sorry, looks like the service was stuck in a crashed state after one of DigitalOcean's maintenance window reboots. I actually got a notification stating that the service was down but it was up when I checked. Seems like I was just fooled by the AppCache. It's up now!

**Comment by jasonpearce** [comment]
Yea! Thank you sir. 

Should you decide that you want to abandon this project, domain, hosting, etc.; I may be willing to carry it on. I am familiar with running VPSes on Vultr and DigitalOcean; domain registration (Hover); DNS and CDN (CloudFlare); and HTML/CSS. Not too strong in JavaScript, but I'd likely just keep your creation up and running. I bet a simple $5/month VPS would be all that is needed.

So if you ever decide to pull the plug, please consider reaching out to either www.jasonpearce.com or @jasonpearce to see if I'm still interested in keeping it alive. Cheers.

**Comment by cxam** [comment]
It's pretty cheap enough to run and maintenance is next to nothing, but I will keep in touch if circumstances change Jason, thanks for the offer.
