### ISSUE TITLE
Your LetsEncrypt.org certificate has expired

### ISSUE THREAD

**Issue by jasonpearce** [cxam/passed.pw#5]
It's nice to see that you are using LetsEncrypt.org. But you might want to check the auto-renew process, for the cert appears to have expired for passed.pw on 2018/04/27. 

Optionally, you could use CloudFlare.com as a CDN. They have a free TLS service as well.

**Comment by cxam** [comment]
Thanks @jasonpearce, I did have a cronjob set for auto-renewal but seems that had failed (related to issues I had in #4).  I'm considering moving this to Firebase hosting as it's just static content. Certificate should be good now.
